import re
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


class SteamIdentitySourceTests(unittest.TestCase):
    """Retail Quake Live owns the local player identity.

    Evidence comes from the user's legitimate Steam installation of
    quakelive_steam.exe 0.1.0.739 and the configs retail wrote for itself under
    ``<steamid>/baseq3`` (headed ``Generated by QUAKE LIVE``, as opposed to the
    ``Generated by FnQL`` files in the same install):

    - the client cvar string cluster holds ``country`` and ``UnnamedPlayer``
      beside the recovered ``cl_*`` registration names,
    - retail persists no ``name`` in either of its configs, while ``rate``,
      ``model``, ``headmodel``, ``sex``, ``color1``, ``color2``, and
      ``cg_predictItems`` all reach ``repconfig.cfg`` and ``cl_anonymous``
      reaches ``qzconfig.cfg``,
    - retail does persist ``seta country "GB"``, into the replicated config,
      which marks it an engine publication rather than a preference,
    - ``PersonaStateChange_t`` is a registered callback and the engine publishes
      ``users.persona.%llu.change``,
    - the retail web UI bundle in ``web.pak`` reads the identity only through
      the read-only ``qz_instance.playerName`` rendered by ``stripColors``, and
      its only ``SetCvar`` targets are ``password``, ``net_port``,
      ``bot_minplayers``, and ``sv_serverType``. There is no rename control.
    """

    @classmethod
    def setUpClass(cls) -> None:
        cls.identity = read("code/qcommon/steam_identity.hpp")
        cls.main = read("code/client/cl_main.cpp")
        cls.webui = read("code/client/cl_webui.cpp")
        cls.platform = read("code/server/sv_platform.cpp")
        cls.header = read("code/client/client.h")
        cls.meson = read("meson.build")
        cls.provider_doc = read("docs/fnql/STEAM_PROVIDER.md")
        cls.cvar_doc = read("docs/fnql/CLIENT_CVAR_COMPATIBILITY.md")

    def test_name_keeps_the_retail_default_and_userinfo_ownership(self) -> None:
        registration = re.search(
            r'Cvar_Get\s*\(\s*"name",\s*([^,]+),\s*([^)]*)\)', self.main
        )
        self.assertIsNotNone(registration)
        self.assertIn("kUnnamedPlayer", registration.group(1))
        self.assertIn("CVAR_USERINFO", registration.group(2))
        self.assertIn("CVAR_ARCHIVE_ND", registration.group(2))
        self.assertIn('kUnnamedPlayer[] = "UnnamedPlayer"', self.identity)

    def test_country_is_published_beside_the_persona_name(self) -> None:
        registration = re.search(
            r'Cvar_Get\s*\(\s*"country",\s*"",\s*([^)]*)\)', self.main
        )
        self.assertIsNotNone(registration)
        self.assertIn("CVAR_USERINFO", registration.group(1))
        self.assertIn("CVAR_ARCHIVE_ND", registration.group(1))
        # Retail wrote country to the replicated config, and CVAR_PROTECTED is
        # what routes a cvar there in Cvar_WriteQLConfigVariables().
        self.assertIn("CVAR_PROTECTED", registration.group(1))
        self.assertIn(
            "target = replicateFile", read("code/qcommon/cvar.c")
        )
        self.assertIn("NormalizeCountryCode", self.identity)
        self.assertIn("NormalizeCountryCode", self.main)

    def test_identity_is_resolved_from_the_provider_persona(self) -> None:
        self.assertIn("FNQL_STEAM_CAP_IDENTITY", self.main)
        self.assertIn("status.persona_name", self.main)
        self.assertIn("status.country", self.main)
        # A signed-out or capability-free provider must not claim the identity.
        self.assertIn("status.local_steam_id != 0", self.main)
        self.assertIn("NormalizePersonaName", self.main)

    def test_identity_is_asserted_before_userinfo_leaves_the_client(self) -> None:
        self.assertIn("void CL_EnforceSteamIdentity( void )", self.main)
        self.assertIn("void CL_RefreshSteamIdentity( void )", self.main)
        for declaration in (
            "void CL_RefreshSteamIdentity( void );",
            "void CL_EnforceSteamIdentity( void );",
            "const char *CL_SteamIdentityName( void );",
            "qboolean CL_SteamIdentityNameLocked( void );",
        ):
            self.assertIn(declaration, self.header)

        # Inside CL_Frame the assertion has to run ahead of both the reliable
        # userinfo update and the connection request that carries userinfo inline.
        frame = self.main[self.main.index("void CL_Frame( int msec, int realMsec )") :]
        enforce = frame.index("CL_EnforceSteamIdentity();")
        check_userinfo = frame.index("CL_CheckUserinfo();")
        resend = frame.index("CL_CheckForResend();")
        self.assertLess(enforce, check_userinfo)
        self.assertLess(check_userinfo, resend)

        # The localhost transition sends userinfo without waiting for a frame.
        local_start = self.main.index('Q_strncpyz( cls.servername, "localhost"')
        local_resend = self.main.index("CL_CheckForResend();", local_start)
        self.assertLess(
            self.main.index("CL_EnforceSteamIdentity();", local_start), local_resend
        )

        # Registration order: the identity is published once the userinfo cvars
        # exist, before an archived value can reach a server.
        self.assertLess(
            self.main.index('Cvar_Get ("cg_predictItems"'),
            self.main.rindex("CL_RefreshSteamIdentity();"),
        )

    def test_rename_attempts_are_reverted_and_explained_once(self) -> None:
        self.assertIn('Cvar_Set2( "name", steamIdentity.name.data(), qtrue )', self.main)
        self.assertIn("steamIdentity.rejected", self.main)
        self.assertIn("follows your Steam profile name", self.main)
        # Adopting a new persona is not a rename attempt.
        self.assertIn("steamIdentity.synced &&", self.main)

    def test_name_lock_is_a_bounded_documented_extension(self) -> None:
        registration = re.search(
            r'Cvar_Get\(\s*"cl_steamNameLock",\s*"1",\s*([^)]*)\)', self.main
        )
        self.assertIsNotNone(registration)
        self.assertIn("CVAR_ARCHIVE_ND", registration.group(1))
        self.assertIn(
            'Cvar_CheckRange( cl_steamNameLock, "0", "1", CV_INTEGER )', self.main
        )
        self.assertIn("cl_steamNameLock", self.provider_doc)
        self.assertIn("cl_steamNameLock", self.cvar_doc)

    def test_webui_player_name_matches_the_published_identity(self) -> None:
        # Retail's qz_instance.playerName is read-only and color-stripped by the
        # UI, so the engine must hand it the same value userinfo carries.
        self.assertIn("CL_SteamIdentityName()", self.webui)
        self.assertNotIn("status.persona_name, (int)bufferSize", self.webui)

    def test_identity_normalization_protects_the_infostring(self) -> None:
        # Info_ValidateKeyValue() rejects these three bytes outright.
        self.assertIn(
            "return value == '\\\\' || value == '\"' || value == ';';", self.identity
        )
        self.assertIn("byte >= 0x20u && byte != 0x7fu", self.identity)
        self.assertIn("TrimPartialUtf8", self.identity)
        self.assertIn("TrimTrailingColorEscape", self.identity)
        # Color escapes survive normalization: retail strips them at render time.
        self.assertNotIn("Q_CleanStr", self.identity)

    def test_retail_hostname_shares_the_persona_normalization(self) -> None:
        # sv_hostname is SERVERINFO, so the retail "<persona>'s Match" default
        # needs the same normalization the client applies to "name".
        self.assertIn('#include "../qcommon/steam_identity.hpp"', self.platform)
        self.assertIn("fnql::identity::NormalizePersonaName", self.platform)
        self.assertIn('"%s\'s Match", persona.data()', self.platform)
        self.assertNotIn("\"%s's Match\", status.persona_name", self.platform)

    def test_identity_bound_matches_the_engine_client_name(self) -> None:
        self.assertIn("std::array<char, MAX_NAME_LENGTH> name{}", self.main)
        self.assertIn("#define\tMAX_NAME_LENGTH\t\t32", read("code/qcommon/q_shared.h"))

    def test_regression_gates_are_registered(self) -> None:
        self.assertIn("tests/steam_identity_tests.cpp", self.meson)
        self.assertIn("tests/steam_identity_source_tests.py", self.meson)


if __name__ == "__main__":
    unittest.main()
